name: pdf_app
description: A smart PDF editor and viewer
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^24.1.41
  file_picker: ^8.0.0
  shared_preferences: ^2.2.3
  pdf: ^3.10.8           # इमेज को पीडीएफ में बदलने के लिए नई लाइब्रेरी
  path_provider: ^2.1.1 # पीडीएफ फाइल को फोन में सेव करने का रास्ता ढूंढने के लिए

flutter:
  uses-material-design: true
